// FOR LOGIN
export const LOGIN_INITIATED = 'LOGIN_INITIATED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const CLEAR_LOGIN_STATE = 'CLEAR_LOGIN_STATE'

// CONSTANTS FOR REGISTRATION PROCESS OF AN ADMIN
export const REGISTRATION_INITIATED = 'REGISTRATION_INITIATED'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'
export const CLEAR_REGISTER_STATE = 'CLEAR_REGISTER_STATE'

// CONSTANTS FOR FETCHING PROCESS OF ADMINS
export const FETCH_ADMINS_INITIATED = 'FETCH_ADMINS_INITIATED'
export const FETCH_ADMINS_SUCCESS = 'FETCH_ADMINS_SUCCESS'

export const FETCH_ADMINS_INITIATED_NO_UPDATES_VERSION = 'FETCH_ADMINS_INITIATED_NO_UPDATES_VERSION'
export const FETCH_ADMINS_SUCCESS_NO_UPDATES_VERSION = 'FETCH_ADMINS_SUCCESS_NO_UPDATES_VERSION'

// CONSTANTS FOR DELETE PROCESS OF AN ADMIN
export const DELETE_ADMIN_INITIATED = 'DELETE_ADMIN_INITIATED'
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS'

// CONSTANTS FOR FETCHING PROCESS OF AN ADMIN
export const FETCH_ADMIN_INITIATED = 'FETCH_ADMIN_INITIATED'
export const FETCH_ADMIN_SUCCESS = 'FETCH_ADMIN_SUCCESS'
export const FETCH_ADMIN_FAILED = 'FETCH_ADMIN_FAILED'

// CONSTANTS FOR UPDATING PROCESS OF AN ADMIN
export const UPDATE_ADMIN_INITIATED = 'UPDATE_ADMIN_INITIATED'
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS'
export const UPDATE_ADMIN_FAILED = 'UPDATE_ADMIN_FAILED'

// CONSTANTS FOR FETCHING PROCESS OF A PROFILE
export const FETCH_PROFILE_INITIATED = 'FETCH_PROFILE_INITIATED'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILED = 'FETCH_PROFILE_FAILED'

// CONSTANTS FOR UPDATING PROCESS OF A PROFILE
export const UPDATE_PROFILE_INITIATED = 'UPDATE_PROFILE_INITIATED'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'

// CONSTANTS FOR UPDATION OF A PROFILE PASSWORD
export const UPDATE_PASSWORD_INITIATED = 'UPDATE_PASSWORD_INITIATED'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED'

// CONSTANTS FOR FETCHING TICKETS
export const FETCH_TICKETS_INITIATED = 'FETCH_TICKETS_INITIATED'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_FAILED = 'FETCH_TICKETS_FAILED'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const VALIDATIION_ERRORS = 'VALIDATIION_ERRORS'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
